apiVersion: apps/v1
kind: Deployment
metadata:
  name: wisecow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wisecow
  template:
    metadata:
      labels:
        app: wisecow
    spec:
      containers:
        - name: wisecow
          image: manojkrishnappa/wisecow:latest
          ports:
            - containerPort: 4499
---
apiVersion: v1
kind: Service
metadata:
  name: wisecow-service
spec:
  selector:
    app: wisecow
  type: NodePort  # Use LoadBalancer if on cloud with LB support
  ports:
    - port: 4499
      targetPort: 4499
      nodePort: 31499  # optional, can be auto-assigned

